spring:
  profiles:
    active:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create # 데이터 초기화를 합니다.
    properties:
      default_batch_fetch_size: 1000
  # h2 를 사용합니다.
  datasource:
    url: ${JDBC_URL:jdbc:h2:mem:testdb}
    driverClassName: org.h2.Driver
    username: ${JDBC_USERNAME:sa}
    password: ${JDBC_PASSWORD:}
  h2:
    console:
      enabled: true
      path: /h2-console
